#!/bin/sh
# Regenerate src/TheoryGrammar/Everything.agda from the files on disk.
# Kept generated rather than hand-written so the list cannot rot.
cd "$(dirname "$0")/src" || exit 1
{
  echo "{-# OPTIONS --lossy-unification -WnoUnsupportedIndexedMatch #-}"
  echo "{- GENERATED by ../gen-everything.sh -- do not edit by hand."
  echo ""
  echo "   Importing every module, so that \`make check\` is a single"
  echo "   command that says whether the tree builds.  Plain \`import\`,"
  echo "   not \`open import\`: nothing is brought into scope, so this"
  echo "   file cannot introduce ambiguity between two applications of a"
  echo "   parameterised module. -}"
  echo "module TheoryGrammar.Everything where"
  echo ""
  find TheoryGrammar -name '*.agda' ! -name 'Everything.agda' \
    | sed -e 's|\.agda$||' -e 's|/|.|g' \
    | sort \
    | sed -e 's|^|import |'
} > TheoryGrammar/Everything.agda
