{-
  THE RESIDUAL EVERY SUBSTRATE ALREADY HAS.

  `Focus` (TheoryGrammar.Fibered) asks for one-hole splittings as data,
  and gets `⊸ᶠ` with β and η both `refl`.  But a promodel already owns
  one family of splittings: `split o m⃗`, the canonical splitting of a
  tuple's own composite.  Fixing a slot `i` and NAMING the complement
  turns those into a `Focus`.  So the residual is not extra structure --
  it is the algebra read backwards, and `⊸ᶠ` at this focus is

      (A ⊸ B) x  =  (rest) → A(rest) → B (op o (tuple x rest))

  i.e. "B, once the hole at slot i is filled with x".

  This is THE residual of `⊗ˢ` exactly when the promodel's splittings are
  generated by `split` -- true on the nose for a free algebra.  Over a
  quotient (bags, sets) it is the residual of the free algebra above,
  which agrees on grammars invariant under the equations.
-}
{-# OPTIONS --lossy-unification #-}
module TheoryGrammar.CanonicalFocus where

open import Cubical.Foundations.Prelude

open import TheoryGrammar.Base
open import TheoryGrammar.Fibered

private variable ℓS ℓ ℓ' ℓX ℓP ℓA ℓB : Level

-- The only datum: how to reassemble a full tuple from the focused
-- element and a naming of the other slots.
record Assembly {S : Type ℓS} {σ : SortedSig S ℓ ℓ'}
                (Fib : Fibered σ ℓX ℓP) (o : σ .ops) (i : σ .arities o)
  : Type (ℓ-max ℓS (ℓ-max ℓ (ℓ-max (ℓ-suc ℓ') ℓX))) where
  field
    Rest   : Type ℓ'
    restOf : Rest → σ .arities o
    tuple  : Fib .carrier (σ .sortOf o i)
           → ((r : Rest) → Fib .carrier (σ .sortOf o (restOf r)))
           → (a : σ .arities o) → Fib .carrier (σ .sortOf o a)

open Assembly public

module Canon {S : Type ℓS} {σ : SortedSig S ℓ ℓ'}
             (Fib : Fibered σ ℓX (ℓ-max ℓ' ℓX)) (P : LaxPoint Fib)
             (o : σ .ops) (i : σ .arities o) (As : Assembly Fib o i) where

  open FibNotation Fib

  focus : Focus Fib o i
  focus .SplitAt _  = (r : As .Rest) → Fib .carrier (σ .sortOf o (As .restOf r))
  focus .whole {x} f = P .op o (As .tuple x f)
  focus .Rest       = As .Rest
  focus .restOf     = As .restOf
  focus .restSlot f = f

  open FocusNotation focus public

  -- ⊸-ELIM at a chosen rest-tuple: plug the hole.  No hypotheses -- the
  -- focus IS the algebra, so applying the residual is application of the
  -- operation.
  plug : {A : (a : σ .arities o) → TheoryTy ℓA (σ .sortOf o a)}
         {B : TheoryTy ℓB (σ .resultSort o)}
         (a⃗ : (r : As .Rest) → Fib .carrier (σ .sortOf o (As .restOf r)))
       → ((r : As .Rest) → A (As .restOf r) (a⃗ r))
       → ⊸ᶠ A B ⊢ (λ x → B (P .op o (As .tuple x a⃗)))
  plug a⃗ pt _ h = h a⃗ pt
