{-# OPTIONS --lossy-unification -WnoUnsupportedIndexedMatch #-}
-- TEMPORARY: Everything minus the concurrent agent's broken WIP.
module TheoryGrammar.EverythingNoWIP where

import TheoryGrammar.Automaton
import TheoryGrammar.Base
import TheoryGrammar.BaseChange
import TheoryGrammar.CanonicalFocus
import TheoryGrammar.CarrierMap
import TheoryGrammar.ChangeOfTheory
import TheoryGrammar.Choice
import TheoryGrammar.ChomskyNormal
import TheoryGrammar.DP
import TheoryGrammar.DP.Nub
import TheoryGrammar.DP.Seq
import TheoryGrammar.DPTests
import TheoryGrammar.Decidable
import TheoryGrammar.Decidable.Additive
import TheoryGrammar.Decidable.Chart
import TheoryGrammar.Decidable.Enumerated
import TheoryGrammar.Decidable.Guarded
import TheoryGrammar.Decidable.Inductive
import TheoryGrammar.Decidable.Listable
import TheoryGrammar.Decidable.Lookahead
import TheoryGrammar.Decidable.Representable
import TheoryGrammar.Decidable.Rule
import TheoryGrammar.Decidable.Splittings
import TheoryGrammar.Decidable.Tensor
import TheoryGrammar.Derivative
import TheoryGrammar.Direct.Associativity
import TheoryGrammar.Direct.Divisibility
import TheoryGrammar.Direct.Group
import TheoryGrammar.Direct.Later
import TheoryGrammar.Direct.Proper
import TheoryGrammar.Distributive
import TheoryGrammar.Domain
import TheoryGrammar.Enumerable
import TheoryGrammar.Enumerable.Listed
import TheoryGrammar.Equations
import TheoryGrammar.Fibered
import TheoryGrammar.Generate
import TheoryGrammar.Generate.FromDec
import TheoryGrammar.Generate.Suite
import TheoryGrammar.GenerateTests
import TheoryGrammar.Gluing
import TheoryGrammar.Gluing.Graded
import TheoryGrammar.Graded
import TheoryGrammar.Grading
import TheoryGrammar.HLevels
import TheoryGrammar.Hoare
import TheoryGrammar.Hylo
import TheoryGrammar.Induction
import TheoryGrammar.Inductive
import TheoryGrammar.Inductive.Consistent
import TheoryGrammar.Inductive.Dual
import TheoryGrammar.Instances.Affine.Base
import TheoryGrammar.Instances.Affine.Codegen
import TheoryGrammar.Instances.Affine.CodegenSub
import TheoryGrammar.Instances.Affine.Contrast
import TheoryGrammar.Instances.Affine.Dead
import TheoryGrammar.Instances.Affine.Syntax
import TheoryGrammar.Instances.Bags.Base
import TheoryGrammar.Instances.Bags.Connectives
import TheoryGrammar.Instances.Bags.JSON
import TheoryGrammar.Instances.Bags.JSONTests
import TheoryGrammar.Instances.Bags.Refinement
import TheoryGrammar.Instances.Dirichlet.Base
import TheoryGrammar.Instances.Dirichlet.Connectives
import TheoryGrammar.Instances.Dirichlet.Divisors
import TheoryGrammar.Instances.Dirichlet.Factorization
import TheoryGrammar.Instances.Dirichlet.Graded
import TheoryGrammar.Instances.Field
import TheoryGrammar.Instances.Field.Base
import TheoryGrammar.Instances.Field.Joint
import TheoryGrammar.Instances.Field.NoPoint
import TheoryGrammar.Instances.Field.Partial
import TheoryGrammar.Instances.Field.Tests
import TheoryGrammar.Instances.Group.Base
import TheoryGrammar.Instances.Group.NoGrading
import TheoryGrammar.Instances.Heap
import TheoryGrammar.Instances.Heap.Adjunction
import TheoryGrammar.Instances.Heap.Array
import TheoryGrammar.Instances.Heap.ArrayTests
import TheoryGrammar.Instances.Heap.Base
import TheoryGrammar.Instances.Heap.Connectives
import TheoryGrammar.Instances.Heap.Emp
import TheoryGrammar.Instances.Heap.Graded
import TheoryGrammar.Instances.Heap.Hoare
import TheoryGrammar.Instances.Heap.Joint
import TheoryGrammar.Instances.Heap.Linear
import TheoryGrammar.Instances.Heap.Located
import TheoryGrammar.Instances.Heap.Precise
import TheoryGrammar.Instances.Heap.Precision
import TheoryGrammar.Instances.Heap.Refinement
import TheoryGrammar.Instances.Heap.Tests
import TheoryGrammar.Instances.Heap.WithInput
import TheoryGrammar.Instances.Lambda
import TheoryGrammar.Instances.Lambda.Adjunctions
import TheoryGrammar.Instances.Lambda.Base
import TheoryGrammar.Instances.Lambda.Binder
import TheoryGrammar.Instances.Lambda.DeBruijn
import TheoryGrammar.Instances.Lambda.Fibered
import TheoryGrammar.Instances.Lambda.Grading
import TheoryGrammar.Instances.Lambda.Initial
import TheoryGrammar.Instances.Lambda.Modes
import TheoryGrammar.Instances.Lambda.Modes.Concat
import TheoryGrammar.Instances.Lambda.Modes.Core
import TheoryGrammar.Instances.Lambda.Modes.Ctx
import TheoryGrammar.Instances.Lambda.Modes.Fold
import TheoryGrammar.Instances.Lambda.Modes.Instances
import TheoryGrammar.Instances.Lambda.Modes.Interleave
import TheoryGrammar.Instances.Lambda.Modes.Laws
import TheoryGrammar.Instances.Lambda.Modes.Overlap
import TheoryGrammar.Instances.Lambda.Modes.Substrate
import TheoryGrammar.Instances.Lambda.Modes.Tests
import TheoryGrammar.Instances.Lambda.Passes.Affine
import TheoryGrammar.Instances.Lambda.Passes.All
import TheoryGrammar.Instances.Lambda.Passes.Dead
import TheoryGrammar.Instances.Lambda.Passes.Decide
import TheoryGrammar.Instances.Lambda.Passes.Eta
import TheoryGrammar.Instances.Lambda.Passes.Framework
import TheoryGrammar.Instances.Lambda.Passes.Inline
import TheoryGrammar.Instances.Lambda.Passes.Rename
import TheoryGrammar.Instances.Lambda.Passes.Tests
import TheoryGrammar.Instances.Lambda.Precision
import TheoryGrammar.Instances.Lambda.Readable
import TheoryGrammar.Instances.Lambda.Residuals
import TheoryGrammar.Instances.Lambda.ScopeCheck
import TheoryGrammar.Instances.Lambda.Scoped
import TheoryGrammar.Instances.Lambda.Signature
import TheoryGrammar.Instances.Lambda.Tests
import TheoryGrammar.Instances.LeakyHeap.Base
import TheoryGrammar.Instances.LeakyHeap.Intuitionistic
import TheoryGrammar.Instances.LinLam.Check
import TheoryGrammar.Instances.LinLam.Codegen
import TheoryGrammar.Instances.LinLam.Context
import TheoryGrammar.Instances.LinLam.DB
import TheoryGrammar.Instances.LinLam.Elim
import TheoryGrammar.Instances.LinLam.IR
import TheoryGrammar.Instances.LinLam.Opt
import TheoryGrammar.Instances.LinLam.Scope
import TheoryGrammar.Instances.LinLam.Surface
import TheoryGrammar.Instances.LinLam.Syntax
import TheoryGrammar.Instances.LinLam.Tests
import TheoryGrammar.Instances.LinTyped
import TheoryGrammar.Instances.LinTyped.Base
import TheoryGrammar.Instances.LinTyped.Check
import TheoryGrammar.Instances.LinTyped.Context
import TheoryGrammar.Instances.LinTyped.Fibered
import TheoryGrammar.Instances.LinTyped.Grading
import TheoryGrammar.Instances.LinTyped.Judgments
import TheoryGrammar.Instances.LinTyped.Readable
import TheoryGrammar.Instances.LinTyped.Signature
import TheoryGrammar.Instances.LinTyped.Tests
import TheoryGrammar.Instances.LinTyped.Types
import TheoryGrammar.Instances.LinTyped.Unique
import TheoryGrammar.Instances.Nat.Base
import TheoryGrammar.Instances.Nat.Connectives
import TheoryGrammar.Instances.Nat.Glue
import TheoryGrammar.Instances.Nat.Graded
import TheoryGrammar.Instances.Nat.Length
import TheoryGrammar.Instances.Nat.LengthFib
import TheoryGrammar.Instances.Nat.NoRefine
import TheoryGrammar.Instances.Nat.Species
import TheoryGrammar.Instances.Nat.Transport
import TheoryGrammar.Instances.Ring.Base
import TheoryGrammar.Instances.Ring.Distributivity
import TheoryGrammar.Instances.Ring.Grading
import TheoryGrammar.Instances.Semimodule.Base
import TheoryGrammar.Instances.Semimodule.Connectives
import TheoryGrammar.Instances.Semimodule.Graded
import TheoryGrammar.Instances.Semimodule.Signature
import TheoryGrammar.Instances.SimplyTyped
import TheoryGrammar.Instances.SimplyTyped.Base
import TheoryGrammar.Instances.SimplyTyped.Check
import TheoryGrammar.Instances.SimplyTyped.Context
import TheoryGrammar.Instances.SimplyTyped.Dependent
import TheoryGrammar.Instances.SimplyTyped.Fibered
import TheoryGrammar.Instances.SimplyTyped.Grading
import TheoryGrammar.Instances.SimplyTyped.Judgments
import TheoryGrammar.Instances.SimplyTyped.Laws
import TheoryGrammar.Instances.SimplyTyped.Readable
import TheoryGrammar.Instances.SimplyTyped.Signature
import TheoryGrammar.Instances.SimplyTyped.Tests
import TheoryGrammar.Instances.SimplyTyped.Types
import TheoryGrammar.Instances.SimplyTyped.Unique
import TheoryGrammar.Instances.Strings.Aligned
import TheoryGrammar.Instances.Strings.Automata
import TheoryGrammar.Instances.Strings.Base
import TheoryGrammar.Instances.Strings.CNFGeneric
import TheoryGrammar.Instances.Strings.CYK
import TheoryGrammar.Instances.Strings.ChartGeneric
import TheoryGrammar.Instances.Strings.Connectives
import TheoryGrammar.Instances.Strings.Decidable
import TheoryGrammar.Instances.Strings.Decomposition
import TheoryGrammar.Instances.Strings.DerivDec
import TheoryGrammar.Instances.Strings.DerivDecTests
import TheoryGrammar.Instances.Strings.Derivative
import TheoryGrammar.Instances.Strings.DerivativeExamples
import TheoryGrammar.Instances.Strings.DyckDec
import TheoryGrammar.Instances.Strings.DyckLex
import TheoryGrammar.Instances.Strings.Enumeration
import TheoryGrammar.Instances.Strings.Examples
import TheoryGrammar.Instances.Strings.Free
import TheoryGrammar.Instances.Strings.Graded
import TheoryGrammar.Instances.Strings.Greedy
import TheoryGrammar.Instances.Strings.KleeneStar
import TheoryGrammar.Instances.Strings.LL
import TheoryGrammar.Instances.Strings.Laws
import TheoryGrammar.Instances.Strings.Levi
import TheoryGrammar.Instances.Strings.Par
import TheoryGrammar.Instances.Strings.Recompose
import TheoryGrammar.Instances.Strings.Refinement
import TheoryGrammar.Instances.Strings.RegExp
import TheoryGrammar.Instances.Strings.SeqUnambig
import TheoryGrammar.Instances.Strings.Shuffle
import TheoryGrammar.Instances.Strings.Transducer
import TheoryGrammar.Instances.Strings.TransducerGuard
import TheoryGrammar.Instances.Strings.TransducerHylo
import TheoryGrammar.Instances.Strings.TransducerMu
import TheoryGrammar.Instances.Traces
import TheoryGrammar.Instances.Traces.Base
import TheoryGrammar.Instances.Traces.Commutative
import TheoryGrammar.Instances.Traces.Decidable
import TheoryGrammar.Instances.Traces.Enumeration
import TheoryGrammar.Instances.Traces.Examples
import TheoryGrammar.Instances.Traces.Mode
import TheoryGrammar.Instances.Traces.ModeTests
import TheoryGrammar.Instances.Traces.Ordered
import TheoryGrammar.Instances.Traces.Protocol
import TheoryGrammar.Instances.Traces.ProtocolTests
import TheoryGrammar.Instances.Traces.Refinement
import TheoryGrammar.Instances.Traces.Shuffle
import TheoryGrammar.Later
import TheoryGrammar.Lifting
import TheoryGrammar.Machine.Example
import TheoryGrammar.Machine.Morphism
import TheoryGrammar.Machine.Refine
import TheoryGrammar.Machine.Signature
import TheoryGrammar.Machine.Theory
import TheoryGrammar.Multiplicative
import TheoryGrammar.Par
import TheoryGrammar.PointedProModel
import TheoryGrammar.Precision
import TheoryGrammar.Quine.Base
import TheoryGrammar.Quine.Family
import TheoryGrammar.Quine.Meta
import TheoryGrammar.Quine.RoundTrip
import TheoryGrammar.Quine.Tiny
import TheoryGrammar.Quine.Trace
import TheoryGrammar.Quine.TraceTests
import TheoryGrammar.Recursion
import TheoryGrammar.Reedy.Base
import TheoryGrammar.Reedy.Polarity
import TheoryGrammar.Refinement
import TheoryGrammar.Refute
import TheoryGrammar.RefuteTests
import TheoryGrammar.Reindex.Base
import TheoryGrammar.Reindex.FrontEnd
import TheoryGrammar.Reindex.LinLam
import TheoryGrammar.Reindex.Pass
import TheoryGrammar.Reindex.Sanity
import TheoryGrammar.Representable
import TheoryGrammar.Restrict
import TheoryGrammar.Result
import TheoryGrammar.Rules
import TheoryGrammar.RulesFib
import TheoryGrammar.SemanticAction
import TheoryGrammar.ShareProbe
import TheoryGrammar.Splitting
import TheoryGrammar.Subgrammar
import TheoryGrammar.Theories.Monoid
import TheoryGrammar.Theories.MonoidSep
import TheoryGrammar.Theories.MonoidStar
import TheoryGrammar.View
