{-# OPTIONS --lossy-unification -WnoUnsupportedIndexedMatch #-}
{- The tensor decision rule, stated in the language rather than by the
   evidence used to establish it.

   `DecReadable` exposes `splitProp`; `DecEnumerable` exposes a `List`
   with a completeness proof.  Both are WITNESSES.  What a client needs
   is the conclusion -- excluded middle for the multiplicative -- and
   the two records are then constructors for one interface, with a
   derivative law a third. -}
open import Cubical.Foundations.Prelude

module TheoryGrammar.Decidable.Rule where

open import Cubical.Data.Sigma
open import Cubical.Data.Sum using (_⊎_; inl; inr)
open import Cubical.Data.Unit

open import TheoryGrammar.Base
open import TheoryGrammar.Fibered
open import TheoryGrammar.Rules
open import TheoryGrammar.RulesFib
open import TheoryGrammar.Par
open import TheoryGrammar.Decidable.Additive
open import TheoryGrammar.Decidable.Tensor
open import TheoryGrammar.Decidable.Enumerated

private variable ℓS ℓ ℓ' ℓX ℓP ℓA : Level

module _ {S : Type ℓS} {σ : SortedSig S ℓ ℓ'} (Fib : Fibered σ ℓX ℓP) where

  open DecFib Fib
  open ParS Fib using (⊗-EM)

  -- THE INTERFACE.  Slotwise decisions yield a decision of the tensor,
  -- whose refuting side is (by `¬⊗-curry`) a product of refutations,
  -- one per decomposition.
  DecTensorRule : Type (ℓ-max ℓ (ℓ-max ℓ' (ℓ-max ℓX (ℓ-max ℓP (ℓ-suc ℓA)))))
  DecTensorRule {ℓA = ℓA} =
    (o : σ .ops) (A : (a : σ .arities o) → TheoryTy ℓA (σ .sortOf o a))
    → ((m : Fib .carrier (σ .resultSort o)) (sp : Fib .Split o m)
       (a : σ .arities o) → Dec⟨ A a ⟩ (Fib .parts o m sp a))
    → ⊗-EM o A

-- ==================================================================
-- Constructor 1: unique readability.  At most one decomposition, so
-- there is nothing to search.  Holds for a free signature.
-- ==================================================================

fromUnique : {S : Type ℓS} {σ : SortedSig S ℓ ℓ'} {Fib : Fibered σ ℓX ℓP}
           → DecReadable Fib ℓA → DecTensorRule Fib {ℓA = ℓA}
fromUnique {Fib = Fib} DR o A d m _ = DecTensor.dec-⊗ DR o A m (d m)

-- ==================================================================
-- Constructor 2: enumerable decompositions.  Finitely many, so the
-- search terminates and completeness turns exhaustion into refutation.
-- Holds for the monoid (length+1 cuts) and for bags (2^n).
-- ==================================================================

fromEnumerable : {S : Type ℓS} {σ : SortedSig S ℓ ℓ'} {Fib : Fibered σ ℓX ℓP}
               → DecEnumerable Fib ℓA → DecTensorRule Fib {ℓA = ℓA}
fromEnumerable DE o A d = enum→⊗EM DE o A d

-- ==================================================================
-- Constructor 3: a derivative law.  BUILT, but only per-promodel.
--
--   δ_c (A ⊗ B) ≅ (A ε & δ_c B) ⊕ (δ_c A ⊗ B)
--
-- establishes the same conclusion with NO search: the `length w + 1`
-- decompositions are the unfolding of this two-case law along the word,
-- so a derivative-based decider does not pay for the enumeration.
--
-- It is NOT a generic constructor, and the reason is structural rather
-- than incidental.  Deciding by differentiation recurses on the
-- CARRIER, so it needs the carrier to be generated by the action --
-- and it re-indexes the slot family at each step (the recursive call is
-- at `δA`, not `A`), so it needs decisions at every element, not at the
-- parts of one splitting.  Neither is available from `Fibered` alone.
--
-- `TheoryGrammar.Derivative` therefore carries the part that IS generic
-- -- `δ` as precomposition, with every additive law refl -- and leaves
-- the ⊗ law as `DerivTensor`, an inversion principle for
-- `Split o (act x)`.  `Instances/Strings/Derivative.agda` discharges it
-- by pattern-matching `Split3`, and derives `strDecTensorδ`, a second
-- and search-free proof of the very `DecTensorRule` that
-- `Strings/Decidable.agda` proves by enumeration.
--
-- It fails for bags: Levi's lemma fails there, so δ does not lift.
-- That is exactly the boundary -- derivative where available,
-- enumeration as the fallback.
-- ==================================================================
